enum UntrustedAppsPolicy {
  'UNTRUSTED_APPS_POLICY_UNSPECIFIED' = 'UNTRUSTED_APPS_POLICY_UNSPECIFIED',
  'DISALLOW_INSTALL' = 'DISALLOW_INSTALL',
  'ALLOW_INSTALL_IN_PERSONAL_PROFILE_ONLY' = 'ALLOW_INSTALL_IN_PERSONAL_PROFILE_ONLY',
  'ALLOW_INSTALL_DEVICE_WIDE' = 'ALLOW_INSTALL_DEVICE_WIDE',
}

enum CommonCriteriaMode {
  'COMMON_CRITERIA_MODE_UNSPECIFIED' = 'COMMON_CRITERIA_MODE_UNSPECIFIED',
  'COMMON_CRITERIA_MODE_DISABLED' = 'COMMON_CRITERIA_MODE_DISABLED',
  'COMMON_CRITERIA_MODE_ENABLED' = 'COMMON_CRITERIA_MODE_ENABLED',
}

export interface IAdvancedSecurityOverrides {
  untrustedAppsPolicy?: UntrustedAppsPolicy;
  commonCriteriaMode?: CommonCriteriaMode;
}
export const defaultValue: Readonly<IAdvancedSecurityOverrides> = {};
