enum PowerButtonActions {
  'POWER_BUTTON_ACTIONS_UNSPECIFIED' = 'POWER_BUTTON_ACTIONS_UNSPECIFIED',
  'POWER_BUTTON_AVAILABLE' = 'POWER_BUTTON_AVAILABLE',
  'POWER_BUTTON_BLOCKED' = 'POWER_BUTTON_BLOCKED',
}

enum SystemErrorWarnings {
  'SYSTEM_ERROR_WARNINGS_UNSPECIFIED' = 'SYSTEM_ERROR_WARNINGS_UNSPECIFIED',
  'ERROR_AND_WARNINGS_ENABLED' = 'ERROR_AND_WARNINGS_ENABLED',
  'ERROR_AND_WARNINGS_MUTED' = 'ERROR_AND_WARNINGS_MUTED',
}

enum SystemNavigation {
  'SYSTEM_NAVIGATION_UNSPECIFIED' = 'SYSTEM_NAVIGATION_UNSPECIFIED',
  'NAVIGATION_ENABLED' = 'NAVIGATION_ENABLED',
  'NAVIGATION_DISABLED' = 'NAVIGATION_DISABLED',
  'HOME_BUTTON_ONLY' = 'HOME_BUTTON_ONLY',
}

enum StatusBar {
  'STATUS_BAR_UNSPECIFIED' = 'STATUS_BAR_UNSPECIFIED',
  'NOTIFICATIONS_AND_SYSTEM_INFO_ENABLED' = 'NOTIFICATIONS_AND_SYSTEM_INFO_ENABLED',
  'NOTIFICATIONS_AND_SYSTEM_INFO_DISABLED' = 'NOTIFICATIONS_AND_SYSTEM_INFO_DISABLED',
  'SYSTEM_INFO_ONLY' = 'SYSTEM_INFO_ONLY',
}

enum DeviceSettings {
  'DEVICE_SETTINGS_UNSPECIFIED' = 'DEVICE_SETTINGS_UNSPECIFIED',
  'SETTINGS_ACCESS_ALLOWED' = 'SETTINGS_ACCESS_ALLOWED',
  'SETTINGS_ACCESS_BLOCKED' = 'SETTINGS_ACCESS_BLOCKED',
}

export interface IKioskCustomization {
  powerButtonActions?: PowerButtonActions;
  systemErrorWarnings?: SystemErrorWarnings;
  systemNavigation?: SystemNavigation;
  statusBar?: StatusBar;
  deviceSettings?: DeviceSettings;
}
export const defaultValue: Readonly<IKioskCustomization> = {};
